name: Bug report
description: Create a report about a bug
title: "[Bug] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "# System"
  - type: input
    id: mc-version
    attributes:
      label: Minecraft version
      placeholder: "ex. 1.20"
    validations:
      required: true
  - type: dropdown
    id: mod-version
    attributes:
      label: Mod version
      options:
        - 1.1
        - 1.2
      multiple: true
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "ex. Windows"
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: " "
  - type: markdown
    attributes:
      value: "# Information"
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: "Steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: " "
  - type: markdown
    attributes:
      value: "# Additions"
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: "If applicable, add screenshots to help explain your problem."
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: "Add any other context about the problem here."
    validations:
      required: false
