name: Crash report
description: Create a report about a crash
title: '[Crash] '
labels:
  - crash
body:
  - type: markdown
    attributes:
      value: '# System'
  - type: input
    id: mc-version
    attributes:
      label: Minecraft version
      placeholder: ex. 1.20
    validations:
      required: true
  - type: dropdown
    id: mod-version
    attributes:
      label: Mod version
      multiple: true
      options:
        - '1.1'
        - '1.2'
        - '1.2.1'
        - '1.2.2'
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: ex. Windows
    validations:
      required: true
  - type: markdown
    attributes:
      value: '<br>'
  - type: markdown
    attributes:
      value: '# Information'
  - type: textarea
    id: mods
    attributes:
      label: Mods
      description: A list of all mods you were using.
      placeholder: |
        - Mod1
        - Mod2
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe what you were doing
      description: >-
        A clear and concise description of what you were doing while the crash
        occurred.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: If applicable, add steps to reproduce the behavior.
      placeholder: |
        1. Go to '...' 
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: markdown
    attributes:
      value: <br>
  - type: markdown
    attributes:
      value: '# Additions'
  - type: input
    id: report
    attributes:
      label: Crash report
      description: >-
        Upload your crash report to [MC Logs](https://mclo.gs) and paste the
        link here.
      placeholder: ex. https://mclo.gs/???????
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
